language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - libgtk2.0-dev
            - g++-7
            - libjack-jackd2-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      install:
        - HOMEBREW_NO_INSTALL_CLEANUP=true brew install jq

cache:
  directories:
  - ./Rack

before_install:
 - RACK_GIT_COMMIT=600268ba65539771dac67d316e2d2a0d999e7b42
 - eval "${MATRIX_EVAL}"
 - cd .. && git clone --recursive https://github.com/VCVRack/Rack.git
 - cd ./Rack && git reset --hard "${RACK_GIT_COMMIT}" && git submodule update && cd ..
 - mv kocmoc-rack-modules ./Rack/plugins/kocmoc-rack-modules
 - cd Rack
 - make dep && make

script:
 - make plugins

