language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - libgtk2.0-dev
            - g++-7
            - libjack-jackd2-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      install:
        - HOMEBREW_NO_INSTALL_CLEANUP=true brew install jq

before_install:
 - eval "${MATRIX_EVAL}"
 - RACK_SDK_GIT_COMMIT=e487820b786ee3a764b9a71bc60c3a31f8105408
 - cd .. && git clone --recursive https://github.com/stellare-modular/vcv-rack-sdk
 - cd ./vcv-rack-sdk && git reset --hard "${RACK_GIT_COMMIT}" && mkdir modules && cd ..
 - mv kocmoc-rack-modules ./vcv-rack-sdk/modules/kocmoc-rack-modules
 - cd ./vcv-rack-sdk/modules/kocmoc-rack-modules
 - export RACK_DIR=../../

script:
 - make dist
